buildVariable: true
familyName: Noto Sans Oriya
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans
  ranges:
    - start: 0x02BC
      end: 0x02BC
- from: Noto Sans
  ranges:
    - start: 0x035A
      end: 0x035A
sources:
- NotoSansOriya.glyphs
